from app.services.parser import GithubProfile
from app.svg.badge import make_stat_badge, make_label_badge, make_profile_badge
from app.svg.chart import make_pie_chart, make_bar_chart, make_repo_card
import base64


def _svg_to_img_tag(svg: str, alt: str = "") -> str:
    """SVG 문자열을 base64 data URI 이미지 태그로 변환"""
    encoded = base64.b64encode(svg.encode("utf-8")).decode("utf-8")
    return f'<img src="data:image/svg+xml;base64,{encoded}" alt="{alt}" />'


def _svg_to_md_img(svg: str, alt: str = "", align: str = "") -> str:
    """마크다운 README에 인라인 SVG 삽입용"""
    encoded = base64.b64encode(svg.encode("utf-8")).decode("utf-8")
    align_attr = f' align="{align}"' if align else ""
    return f'<img src="data:image/svg+xml;base64,{encoded}" alt="{alt}"{align_attr} />'


def build_readme(
    profile: GithubProfile,
    chart_style: str = "pie",           # "pie" | "bar"
    show_repos: bool = True,
    show_languages: bool = True,
    show_stats: bool = True,
    custom_title: str = "",
    custom_bio: str = "",
) -> str:
    """
    GithubProfile 데이터로 README.md 마크다운 문자열 생성
    """
    lines: list[str] = []
    
    # ── 헤더 ──────────────────────────────────────────
    title = custom_title or f"Hi there, I'm {profile.name} 👋"
    lines += [
        f"# {title}",
        "",
    ]
    
    # ── 프로필 배지 ───────────────────────────────────
    if show_stats:
        profile_svg = make_profile_badge(
            name=profile.name,
            username=profile.username,
            followers=profile.followers,
            following=profile.following,
            public_repos=profile.public_repos,
        )
        lines += [
            _svg_to_md_img(profile_svg, alt="profile badge", align="right"),
            "",
        ]
    
    # ── 소개 (bio) ────────────────────────────────────
    bio_text = custom_bio or profile.bio
    if bio_text:
        lines += [
            f"> {bio_text}",
            "",
        ]
    
    # ── 통계 배지 ─────────────────────────────────────
    if show_stats:
        followers_svg = make_stat_badge("Followers", profile.followers, width=160)
        following_svg = make_stat_badge("Following", profile.following, width=160)
        commits_svg   = make_stat_badge("Recent Commits", profile.recent_commit_count, width=190)

        lines += [
            "## 📊 Stats",
            "",
            _svg_to_md_img(followers_svg, "followers") + "&nbsp;" +
            _svg_to_md_img(following_svg, "following") + "&nbsp;" +
            _svg_to_md_img(commits_svg, "commits"),
            "",
        ]
    
    # ── 언어 차트 ─────────────────────────────────────
    if show_languages and profile.lang_ratio:
        if chart_style == "bar":
            chart_svg = make_bar_chart(profile.lang_ratio)
        else:
            chart_svg = make_pie_chart(profile.lang_ratio)
        
        lines += [
            "## 🗂️ Languages",
            "",
            _svg_to_md_img(chart_svg, "language chart"),
            "",
        ]
    
    # ── 언어 라벨 배지 ────────────────────────────────
    if show_languages and profile.top_languages:
        from app.core.constants import LANGUAGE_COLORS, DEFAULT_COLOR
        badge_tags = []
        for lang in profile.top_languages:
            color = LANGUAGE_COLORS.get(lang, DEFAULT_COLOR)
            svg = make_label_badge(lang, color, width=90)
            badge_tags.append(_svg_to_md_img(svg, lang))
        
        lines += [
            " ".join(badge_tags),
            "",
        ]
    
    # ── 스타 레포 카드 ────────────────────────────────
    if show_repos and profile.top_repos:
        lines += [
            "## ⭐ Top Repositories",
            "",
        ]
        for repo in profile.top_repos:
            card_svg = make_repo_card(
                name=repo.name,
                description=repo.description,
                stars=repo.stars,
                language=repo.language,
                url=repo.url,
            )
            lines += [
                _svg_to_md_img(card_svg, repo.name),
                "",
            ]
    
    # ── 푸터 ──────────────────────────────────────────
    lines += [
        "---",
        "",
        f"<p align='center'>Generated by "
        f"<a href='https://github.com/Dev-2A/github-readme-gen'>github-readme-gen</a> 🤖</p>",
        "",
    ]
    
    return "\n".join(lines)